import { OAuthProvider } from "@/providers/OAuthProviderSSR";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SignedInProvider } from "@/providers/SignedInProvider";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "@/providers/SessionProvider";
import { getSession } from "@/lib/atproto-session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  console.log("Session", session);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <OAuthProvider>
          <SessionProvider session={session}>
            <SignedInProvider>{children}</SignedInProvider>
          </SessionProvider>
          <Toaster />
        </OAuthProvider>
      </body>
    </html>
  );
}
